### PR TITLE
Changed events this plugin listens to, making it much faster, and by this, less laggy.

### PR DESCRIPTION
**Pull request by mamut**
Instead of listening to CursorHold it now listens to CursorMoved -- ut variable is probably no longer needed.

### CODE REVIEW

**Comment by lilydjwg** [comment]
Hi KrzysztofUrban, thank you for the idea. I have [another fork](https://github.com/lilydjwg/colorizer) of this plugin, and your idea works very well!

**Comment by ap** [comment]
Hi,

I’ve added this in [my fork](https://github.com/ap/vim-css-color).

**Comment by skammer** [comment]
Thanks for all your patches guys. I've been really busy last couple of months. Great to know my plugin was mentioned here on github. I promise to spend more time fixing bugs now ;)

**Comment by skammer** [comment]
Thanks for all your patches guys. I've been really busy last couple of months. Great to know my plugin was mentioned here on github. I promise to spend more time fixing bugs now ;)

**Pull request merged**
